markdown: Kramdown
highligher: false
permalink: /:categories/:title
exclude: ["readme.md", "Gemfile", "Gemfile.lock", "config.ru"]
name: Paul May
description: Paul May's Blog
url: http://www.paulmay.org

# this goes inside _config.yml. Change as required
navigation:
- text: About
  url: /about/index.html
  cleanurl: /about/
  layout: home
- text: Blog
  url: /blog/index.html
  cleanurl: /blog/
  layout: post
- text: Work
  url: /work/index.html
  cleanurl: /work/
  layout: project