markdown: Kramdown
highligher: false
permalink: /:categories/:title
exclude: ["readme.md", "Gemfile", "Gemfile.lock", "config.ru"]
name: Paul May
description: Paul May's Blog
url: http://www.paulmay.org

# this goes inside _config.yml. Change as required
navigation:
- text: Home
  url: /
  cleanurl: /
  layout: home
- text: About
  url: /about/index.html
  cleanurl: /about/
  layout: about
# - text: Articles
#   url: /articles/index.html
#   cleanurl: /blog/
#   layout: post
# - text: Work
#   url: /work/index.html
#   cleanurl: /work/
#   layout: project